### ISSUE TITLE
Cannot find  ZX Spectrum 128K, PAL

### ISSUE THREAD

**Issue by dobrMAN** [Dotneteer/spectnetvsc#1]
I try open sample in buildin emulator, but get this error...

> Cannot find  ZX Spectrum 128K, PAL

I use Linux Mint 19

**Comment by dobrMAN** [comment]
Ok, i found issue. In linux file names is case sensivity, and rom's in projects have names like "ZXSpectrum48.rom" (with capital X), but in SpectrumModels.ts we have equation with "ZxSpectrum48.rom" (With lowercase x)...

**Comment by Dotneteer** [comment]
Thanks @dobrMAN for the bug report :-). I will soon fix it.

**Comment by Dotneteer** [comment]
Fixed the https://github.com/Dotneteer/spectnetvsc-samples and https://github.com/Dotneteer/generator-zxspectrum projects to provide correct `.rom` and `.disann` file names.

**Comment by kerberosdelhades** [comment]
Hi, @Dotneteer: I'm still getting the same error as @dobrMAN (Cannot find ZX Spectrum 48K, PAL). Version 0.1.6-alpha, installed in Ubuntu 18.10 (cosmic) with VS code 1.36.0.
I cannot figure out if where I have to modify the names to make it work:

`~/.vscode/extensions/dotneteer-vsc.spectnetvsc-0.1.6$ grep -r ZxSpectrum48 * | grep rom
out/spectrumemu/machine/SpectrumModels.js:                romName: "ZxSpectrum48",
out/spectrumemu/machine/SpectrumModels.js:                romName: "ZxSpectrum48",`

Thanks in advance,

**Comment by kerberosdelhades** [comment]
I finally solved it in the root of the proyect, inside `.zxspectrum`:
`~/CodigoFuente/ZX_Spectrum/assembler/spectnetvsc-samples/ZxSpectrum48GettingStarted/.zxspectrum$ mv ZXSpectrum48.disann ZxSpectrum48.disann
`~/spectnetvsc-samples/ZxSpectrum48GettingStarted/.zxspectrum$ mv ZXSpectrum48.rom ZxSpectrum48.rom `
